### ISSUE TITLE
Loading error in forge 1.20.1

### ISSUE THREAD

**Issue by CsillaAria** [MehVahdJukaar/WoodGood#225]
Crash report, and last log here
[crash-2023-08-20_20.46.26-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/12390267/crash-2023-08-20_20.46.26-fml.txt)
[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/12390270/latest.log)

If there is anything else you need let me know, and I'll try to get it for you.

**Comment by MehVahdJukaar** [comment]
Fixed

**Comment by CsillaAria** [comment]
Thank you!

**Comment by LiAuTraver** [comment]
> Fixed

i encountered error too.
it mainly shows that

 '"java.lang.NoSuchMethodError: 'net.mehvahdjukaar.moonlight.api.misc.RegSupplier net.mehvahdjukaar.moonlight.api.platform.RegHelper.registerCreativeModeTab(net.minecraft.resources.ResourceLocation, boolean, java.util.function.Consumer)'"

 failed to load,which i suggest  related to the registration of  creative mode tab.

do i need to update my forge?(47.1.0) or the moonlight API library?

everycomp version 2.6.2.

wish it'll soon be ok. 

thanks!

**Comment by MehVahdJukaar** [comment]
Are you sure you got latest moonlgiht version?

**Comment by LiAuTraver** [comment]
Thanks! But some error remains.
I update my moonlight lab to the newest version which was released today(or yesterday,because i am a chinese :)we may in the opposite of the earth hahah ),and it works fine except this.
As you can see, some of the variants are not in their proper shapes(but they function, e.g. cabinets could store items) .Was this caused by the old version of forge(47.1.0)? my moonlight and everycomp are up to date.
<img width="1280" alt="image" src="https://github.com/MehVahdJukaar/WoodGood/assets/63725840/f35b1797-7d30-4d15-998e-e2b1fc417346">

**Comment by MehVahdJukaar** [comment]
i know I'm waiting for people responsible for each module to change the textures as many mods have changed their texture formats. This is not a big issue as it doesnt crash and can be changed with texture packs

**Comment by LiAuTraver** [comment]
Thanks.
Wish things will be alright.

**Comment by Xelbayria** [comment]
Friendly Remind: if the problem is resolved, then please close this. Thanks!
