### ISSUE TITLE
Crashes with Macaw's Furniture on 1.20.1/Forge

### ISSUE THREAD

**Issue by 1straycat** [MehVahdJukaar/WoodGood#251]
Having both Macaw's Furniture v3.2.0 and Every Compat v2.6.5 in the mods folder causes a crash to occur during startup, claiming Every Compat failed to load correctly.
Crash report: https://pastebin.com/YaNv1J4h
Latest.log: https://pastebin.com/UXski0ra

**Comment by Gamemassa** [comment]
Yeah, I'm having this issue as well.

**Comment by Xelbayria** [comment]
The issue may be similar to the problem with 1.18.2 and 1.19.2. It was just a small fixes. I'll investigate what's changed and apply the fixes. 

---
EDIT: 
Confirmed.  `Macaw's Furniture Module` caused EC to crash. Something to do with "Null". 

---
EDIT 2: 
Ok found the cause. It looks like I'll have to consult MehVahdJukaar about the cause, it's a major change on how it add the items to Creative Tab (where you get stuff from tab via Creative mode).

**Comment by LiAuTraver** [comment]
same issue.

**Comment by Xelbayria** [comment]
@Gamemassa @LiAuTraver @1straycat 

Please change your forge version to `47.1.0` (recommended version) and see if you have no crash. if you got crash. try the latest version of forge to see if there is no crash. 

or you can try neoforge (forge will be no longer updated from 1.20.1 onward.

**Comment by 1straycat** [comment]
@Xelbayria

Just tested, Forge 47.1.0, 47.1.46, and NeoForge 47.1.75 all give the exact same loading error, sadly... let me know if you want to see the crash reports anyway.

**Comment by Xelbayria** [comment]
I wasn't able to replicate that issue on my side anymore. I am not the only one, another guy also tested all of the forge versions and had no crashes. 

an extra crash report is not needed. it should be the exactly same as your first crash log

**Comment by Gamemassa** [comment]
@Xelbayria I also have Forge 47.1.46 and I'm still getting the same crash as @1straycat. ~~Haven't tried NeoForge yet.~~ Ok, I also tried NeoForge 47.1.76 and got the same crash as well.

**Comment by Xelbayria** [comment]
I found out that the mod, v2.6.5 via CurseForge doesn't have the updated Macaw's Furniture Module. I'll be uploading the new version of the mod for 1.20.1 with two things: 
- Chipped with fixed recipes
- updated Macaw's furniture Module (that should fix the crash)

---
EDIT: 
I've uploaded the v2.6.6 to CF, <strike>it will take a while to be approved. </strike>

it's approved. You can try the v2.6.6 to see if Minecraft no longer crash

**Comment by Gamemassa** [comment]
~~I updated Every Compat in my custom modpack, and suddenly I'm getting this weird crash (latest.log below). I had also updated Xaero's Minimap and World Map, Compact Storage, ChoiceTheorem's Overhauled Villages and REI, but I don't think any of these or Every Compat are causing the crash because I reverted them all again and I'm still getting it.~~

https://gist.github.com/Gamemassa/d5b80c667e05e85b0325f6e4afed9242

Turns out the issue was SuperMartijn's Fusion (Connected Textures). I had mistakenly put the latest version of Fusion for MC _1.12.1_ in my modpack and Minecraft **_really_** did not like it.

Also, I can actually confirm, Every Compat 2.6.6 is working with Macaw's Furniture.

**Comment by 1straycat** [comment]
The crash resolved for me with v2.6.6!

**Comment by GreenForzeGaming** [comment]
@Xelbayria i still have this issue
https://github.com/MehVahdJukaar/WoodGood/issues/261

**Comment by Xelbayria** [comment]
@1straycat 

Friendly Reminder: Please close this issue if you are satisfied with the issue being resolved.

**Comment by Xelbayria** [comment]
I'll assume it's solved, I'll be closing this
