### ISSUE TITLE
[🐞]: Failed to generate recipe for 

### ISSUE THREAD

**Issue by fionera** [MehVahdJukaar/WoodGood#500]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

everycomp-1.20-2.6.53

### Moonlight Lib Version

moonlight-1.20-2.11.12

### Issue with mods

Thats a difficult question. I saw issues with these even tho everything works

- [Macaw's Fences and Walls](https://modrinth.com/mod/GmwLse2I) 1.1.1
- [Hybrid Aquatic](https://modrinth.com/mod/HH4FjUqN) 1.3.2
- [Create](https://modrinth.com/mod/Xbc0uyRg) 0.5.1-f-build.1417+mc1.20.1

### Issue Detail

Basically what the title says, the logs gets spammed every time the world generator gets initialized. Since I have "World Preview" installed this happens farirly often

### OPTIONAL: Latest.log | Crash-report Attachment

<details><summary>Portion of latest.log</summary>
<p>

```
[03:18:11] [pool-10-thread-1/ERROR]: Failed to generate recipe for c/hybrid-aquatic/driftwood_window_pane:
java.lang.UnsupportedOperationException: Could not convert output item oak_window_pane from type minecraft:oak to hybrid-aquatic:driftwood
	at net.mehvahdjukaar.moonlight.core.recipe.ShapedRecipeTemplate.createSimilar(ShapedRecipeTemplate.java:62) ~[moonlight-1.20-2.11.12-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.core.recipe.ShapedRecipeTemplate.createSimilar(ShapedRecipeTemplate.java:23) ~[moonlight-1.20-2.11.12-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.recipe.IRecipeTemplate.createSimilar(IRecipeTemplate.java:23) ~[moonlight-1.20-2.11.12-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.misc.ResourcesUtils.lambda$addBlocksRecipes$9(ResourcesUtils.java:361) ~[everycomp-1.20-2.6.53-fabric.jar:?]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at net.mehvahdjukaar.every_compat.misc.ResourcesUtils.addBlocksRecipes(ResourcesUtils.java:350) ~[everycomp-1.20-2.6.53-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.api.AbstractSimpleEntrySet.generateRecipes(AbstractSimpleEntrySet.java:174) ~[everycomp-1.20-2.6.53-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.lambda$addDynamicServerResources$7(SimpleModule.java:96) ~[everycomp-1.20-2.6.53-fabric.jar:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(Unknown Source) ~[?:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.addDynamicServerResources(SimpleModule.java:94) ~[everycomp-1.20-2.6.53-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ServerDynamicResourcesHandler.lambda$regenerateDynamicAssets$0(ServerDynamicResourcesHandler.java:40) ~[everycomp-1.20-2.6.53-fabric.jar:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.forAllModules(EveryCompat.java:73) ~[everycomp-1.20-2.6.53-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ServerDynamicResourcesHandler.regenerateDynamicAssets(ServerDynamicResourcesHandler.java:38) ~[everycomp-1.20-2.6.53-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:129) ~[moonlight-1.20-2.11.12-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:83) ~[moonlight-1.20-2.11.12-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.11.12-fabric.jar:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(Unknown Source) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.11.12-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.20-2.11.12-fabric.jar:?]
	at net.minecraft.class_6861.handler$hjh000$moonlight$dynamicPackEarlyReload(class_6861.java:2540) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237$class_7238.method_42099(class_7237.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:29) ~[client-intermediary.jar:?]
	at caeruleusTait.world.preview.client.gui.screens.PreviewTab.previewWorldCreationContext(PreviewTab.java:100) ~[world_preview-fabric-1.20.1-1.2.2.jar:?]
	at caeruleusTait.world.preview.client.gui.screens.PreviewContainer.lambda$updateSettings$20(PreviewContainer.java:348) ~[world_preview-fabric-1.20.1-1.2.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

</p>
</details> 

### OPTIONAL: To Produce

1) Install Mods
2) Generate a World
3) See error spam

**Comment by fionera** [comment]
I would suggest allowing a blacklist of items that can appear as output item (e.g. prevent oak_window_pane to be handled) or not throwing an exception but instead logging a smaller message, bonus points if that only happens once per game instance

**Comment by Xelbayria** [comment]
I cannot replicate the problem on my side. First, just use: 
- Every Comp
- Moonlight
- with the 3 mods you've listed that have issues with EveryComp

run the Minecraft and check if there is no error in generating the recipe. Then one of the mods in your modpack is screwing up the generation of the recipe

**Comment by Xelbayria** [comment]
Haven't heard from you for a while, is there any news regarding this issue?

**Comment by fionera** [comment]
Yeah sorry lots of "no time" right now. I will try to get to it today or tomorrow

**Comment by fionera** [comment]
Ok after a long "tomorrow" I finally found time to debug this. This is also requires https://github.com/Fuzss/diagonalwalls . I have this mod list (all of them the newest version):

<details><summary>ModList</summary>
<p>

- Dawn API
- Diagonal Walls
- Every Compat
- Fabric API
- Forge Config API Port
- Macaw's Fences and Walls
- Macaw's Holidays
- Moonlight
- Puzzles Lib
- World preview (tho just do make it easy to reproduce)

</p>
</details>

**Comment by Xelbayria** [comment]
I'll test the modlist on my side and will let u know how it turned out. 

### UPDATE:

With the modlist you provided with **Hybrid Aquatic** and **Create**, I can't reproduce. I am wondering what mods that require **Dawn API**, that's just a library mod.

**Comment by fionera** [comment]
Can you try with the new list I sent? I had the initial one made from the errors but I could reproduce it with the lower one. Dawn API was just still in the list because I forgot it wasn't needed for any of them. Can still reproduce without.

<details>

```
[21:05:07] [main/INFO]: Loading 90 mods:
	- diagonalwalls 8.0.3
	   \-- diagonalblocks 8.0.5
	- everycomp 1.20-2.6.55
	   |-- porting_lib_accessors 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_base 2.3.0+1.20.1
	   |    |-- porting_lib_attributes 2.3.0+1.20.1
	   |    |-- porting_lib_common 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    |-- porting_lib_entity 2.3.0+1.20.1
	   |    |-- porting_lib_fluids 2.3.0+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.0+1.20.1
	   |    |-- porting_lib_transfer 2.3.0+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_client_events 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_config 2.3.0+1.20.1
	   |    |-- com_electronwill_night-config_core 3.6.6
	   |    |-- com_electronwill_night-config_toml 3.6.6
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_extensions 2.3.0+1.20.1
	   |    |-- porting_lib_attributes 2.3.0+1.20.1
	   |    |-- porting_lib_common 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_lazy_registration 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_loot 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_networking 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_registries 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_tool_actions 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   \-- porting_lib_utility 2.3.0+1.20.1
	        \-- porting_lib_core 2.3.0+1.20.1
	- fabric-api 0.92.1+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- forgeconfigapiport 8.0.0
	- java 17
	- mcwfences 1.1.1
	- mcwholidays 1.1.0
	- minecraft 1.20.1
	- moonlight 1.20-2.11.22
	- puzzleslib 8.1.19
	   \-- puzzlesaccessapi 8.0.7
	- world_preview 1.2.2
```

</details>

<details>

```
[21:05:26] [Render thread/ERROR]: Failed to generate recipe for mcf/mcwholidays/mixed_oak_hedge:
java.lang.UnsupportedOperationException: Could not convert output item oak_hedge from type minecraft:oak to mcwholidays:mixed_oak
```

</details>

**Comment by Xelbayria** [comment]
The cause is **Diagonal Wall**, There is nothing wrong with **EveryComp** or **Moonlight Lib**. idk why. This require further investigation. 

_hedge_ is considered to be a "wall" so **Diagonal Wall** should have supported that but somehow screw up the generation of recipes via **Moonlight Lib**. 

**World Preview** is not related to this issue.

**Comment by Xelbayria** [comment]
I no longer have the issue on my side. **Macaw's Fences & Walls (MCF)** have been updated to v1.1.2

**EveryComp (EC)** is also updated to support v1.1.2 but won't support the older version anymore. Can you test on your side with the latest version when **Moonlight Lib** & **EveryComp** is out on Curseforge & Modrinth

## UPDATE: 

interesting. The theory is the _hedge_ does not have the tags and that may be the cause of why **Diagonal Wall** screwing up the generation of recipes.   the tags for hedge is `minecraft:fences` which is what allows them to behave like fences or walls. 
I'm sure that **Diagonal Wall** used the tag to find and apply the diagonal behaviour to all of the fences with the tag. 

I decided to test to see if the updated **EC** and **MCF** solved this problem. 

Anyway, this should fix the problem.

**Comment by fionera** [comment]
The issue still exists when I run the mod list (updated to the newest versions ofc). And additionally I get a _lot_ of logs like this now

```
[21:54:11] [Worker-Main-7/WARN]: Unable to bake model: 'everycomp:mcf/mcwholidays/mixed_oak_hedge#east=tall,north=none,south=none,up=true,waterlogged=false,west=none': java.lang.RuntimeException: Unknown value 'true' for property 'north' on 'Block{everycomp:mcf/mcwholidays/mixed_oak_hedge}' in 'true'
[21:54:11] [Worker-Main-7/WARN]: Unable to bake model: 'everycomp:mcf/mcwholidays/yellow_oak_hedge#east=tall,north=tall,south=tall,up=true,waterlogged=false,west=low': java.lang.RuntimeException: Unknown value 'true' for property 'north' on 'Block{everycomp:mcf/mcwholidays/yellow_oak_hedge}' in 'true'
[21:54:11] [Worker-Main-7/WARN]: Unable to bake model: 'everycomp:mcf/mcwholidays/red_oak_hedge#east=tall,north=tall,south=low,up=true,waterlogged=false,west=low': java.lang.RuntimeException: Unknown value 'true' for property 'north' on 'Block{everycomp:mcf/mcwholidays/red_oak_hedge}' in 'true'
[21:54:11] [Worker-Main-7/WARN]: Unable to bake model: 'everycomp:mcf/mcwholidays/snowy_oak_hedge#east=none,north=tall,south=tall,up=true,waterlogged=false,west=tall': java.lang.RuntimeException: Unknown value 'true' for property 'north' on 'Block{everycomp:mcf/mcwholidays/snowy_oak_hedge}' in 'true'
```

**Comment by Xelbayria** [comment]
I haven't uploaded **EveryComp** to Curseforge or Modrinth yet.  I'll let u know when. 

this should be fixed in **v2.6.62**

**Comment by Xelbayria** [comment]
Please let me know if **v2.6.62** has fixed the problem. It's out on Curseforge and modrinth

**Comment by Xelbayria** [comment]
Haven't heard from you, does the latest version fix this issue?

**Comment by fionera** [comment]
Sorry for the delayed answer. The errors with mcw's mods are gone but I still see some with chipped. I will try to make a minimal reproduce for that one

**Comment by fionera** [comment]
Nevermind, it also reports that for the other items too. 

<details>

```
[03:52:00] [main/INFO]: Loading 92 mods:
	- diagonalfences 8.1.4
	   \-- diagonalblocks 8.0.5
	- diagonalwalls 8.0.3
	   \-- diagonalblocks 8.0.5
	- everycomp 1.20-2.6.66
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_attributes 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_base 2.3.4+1.20.1
	   |    |-- com_electronwill_night-config_core 3.6.6
	   |    |-- com_electronwill_night-config_toml 3.6.6
	   |    |-- porting_lib_config 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    |-- porting_lib_fluids 2.3.4+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_utility 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_common 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_entity 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |-- porting_lib_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_model_generators 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    |-- porting_lib_data 2.3.4+1.20.1
	   |    |-- porting_lib_model_materials 2.3.4+1.20.1
	   |    \-- porting_lib_utility 2.3.4+1.20.1
	   |-- porting_lib_model_loader 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_models 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    \-- porting_lib_fluids 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_obj_loader 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   \-- porting_lib_transfer 2.3.4+1.20.1
	        |-- porting_lib_core 2.3.4+1.20.1
	        \-- porting_lib_fluids 2.3.4+1.20.1
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- forgeconfigapiport 8.0.0
	- java 17
	- mcwfences 1.1.2
	- mcwholidays 1.1.0
	- minecraft 1.20.1
	- moonlight 1.20-2.12.6
	- puzzleslib 8.1.21
	   \-- puzzlesaccessapi 8.0.7
	- world_preview 1.3.0
```

</details>

<details>	
	
```
	[03:52:18] [pool-5-thread-1/ERROR]: Failed to generate recipe for mcf/mcwholidays/snowy_spruce_hedge:
java.lang.UnsupportedOperationException: Could not convert output item oak_hedge from type minecraft:oak to mcwholidays:snowy_spruce
	at net.mehvahdjukaar.moonlight.core.recipe.ShapedRecipeTemplate.createSimilar(ShapedRecipeTemplate.java:62) ~[moonlight-1.20-2.12.6-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.core.recipe.ShapedRecipeTemplate.createSimilar(ShapedRecipeTemplate.java:23) ~[moonlight-1.20-2.12.6-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.recipe.IRecipeTemplate.createSimilar(IRecipeTemplate.java:23) ~[moonlight-1.20-2.12.6-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.misc.ResourcesUtils.lambda$addBlocksRecipes$9(ResourcesUtils.java:362) ~[everycomp-1.20-2.6.66-fabric.jar:?]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at net.mehvahdjukaar.every_compat.misc.ResourcesUtils.addBlocksRecipes(ResourcesUtils.java:351) ~[everycomp-1.20-2.6.66-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.api.AbstractSimpleEntrySet.generateRecipes(AbstractSimpleEntrySet.java:225) ~[everycomp-1.20-2.6.66-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.lambda$addDynamicServerResources$7(SimpleModule.java:99) ~[everycomp-1.20-2.6.66-fabric.jar:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(Unknown Source) ~[?:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.addDynamicServerResources(SimpleModule.java:97) ~[everycomp-1.20-2.6.66-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ServerDynamicResourcesHandler.lambda$regenerateDynamicAssets$0(ServerDynamicResourcesHandler.java:40) ~[everycomp-1.20-2.6.66-fabric.jar:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.forAllModules(EveryCompat.java:78) ~[everycomp-1.20-2.6.66-fabric.jar:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ServerDynamicResourcesHandler.regenerateDynamicAssets(ServerDynamicResourcesHandler.java:38) ~[everycomp-1.20-2.6.66-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.reloadResources(DynResourceGenerator.java:129) ~[moonlight-1.20-2.12.6-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceGenerator.onEarlyReload(DynResourceGenerator.java:83) ~[moonlight-1.20-2.12.6-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.lambda$postEvent$1(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.12.6-fabric.jar:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(Unknown Source) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.fabric.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:27) ~[moonlight-1.20-2.12.6-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.20-2.12.6-fabric.jar:?]
	at net.minecraft.class_6861.handler$bdh000$moonlight$dynamicPackEarlyReload(class_6861.java:1044) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.<init>(class_6861.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237$class_7238.method_42099(class_7237.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:29) ~[client-intermediary.jar:?]
	at caeruleusTait.world.preview.client.gui.screens.PreviewTab.previewWorldCreationContext(PreviewTab.java:100) ~[world_preview-fabric-1.20.1-1.3.0.jar:?]
	at caeruleusTait.world.preview.client.gui.screens.PreviewContainer.lambda$updateSettings$24(PreviewContainer.java:423) ~[world_preview-fabric-1.20.1-1.3.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

</details>

**Comment by Xelbayria** [comment]
I cannot replicate the problem on my side. I know you are busy and have little times.  Try and see if you can disable all of mods with a few mods enabled.  so you can enable 1-4 mods a time to load world until you got the error spam. The culprit need to be isolated. One of the mods is somehow screwing up the generation of recipe.

**Comment by fionera** [comment]
As listed in my previous message I can reproduce it with just Macaw's Fences, Macaw's Holidays, Diagonal Walls, Diagonal Fences and Everycomp. All of them are in their newest version

**Comment by Xelbayria** [comment]
I ran a simple test by actually crafting item/block. The result is I can craft the hedge on my side even with the error in the log. These errors are "false positive". Idk why it happened. The recipe are generated for these hedges. Can you confirm that you can craft the hedge. If you have no problems, then yea. For now, just ignore these errors.

This issue should be related to **Moonlight lib**. I'll talk to MehVahdJukaar.

**Comment by Xelbayria** [comment]
Just checking, do you still get the false errors in the logging?

**Comment by Xelbayria** [comment]
since there is no replying. will be closing this.
