### ISSUE TITLE
[🐞]: Re:Deco Broken Loot Tables

### ISSUE THREAD

**Issue by tikiMC** [MehVahdJukaar/WoodGood#969]
### Code of Conduct

- [x] Always check you are using the latest version of the mods and its dependencies
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycompat-1.20-2.8.8-forge

### Moonlight Lib Version

moonlight-1.20-2.14.10-forge

### Issue with mods

Re:Deco redeco-1.14.1-forge

### Issue Detail

Re:Deco has items called <color> fabric which you can place on blocks like chairs and benches to add a cushion to them and some color. I've discovered that the EC wood types do not give this fabric back when you break the block as the base mod does.

### OPTIONAL: To Produce

https://github.com/user-attachments/assets/8062d26e-3752-442a-8683-89cc25b9b47f

**Comment by Xelbayria** [comment]
oh i know what's the problem. thanks for the reporting.

**Comment by Xelbayria** [comment]
## FIXED in v2.8.9

**Comment by tikiMC** [comment]
Hey I didn't play around enough with Re:Deco myself to know this, but I just found out you can add fabric to the mods Pedestals, Display Cases, and Sword Mounts. I just checked with v2.8.9 and these are still broken unfortunately.

**Comment by Xelbayria** [comment]
I just tested it on my side, it's working properly. for chair, bench, and stool. Are there other blocks that have cushion or fabric but incorrect loot_table? 

i'll check on display case, Sword Mounts, and pedestals

**Comment by tikiMC** [comment]
yah sorry I wasn't clear, the chairs, benches, etc are fixed but the above mentioned, case, mount and pedestal are still broken in 2.8.9

**Comment by Xelbayria** [comment]
yeah i've checked the wiki of Re: Deco and these 3 can be "Upholstered" with fabric. so i've added the same fix to these pedestal, mount, cases


tbh, i thought it was just 3. idk there are 3 more blocks that can use fabric

**Comment by Xelbayria** [comment]
## UPDATED & FIXED in v2.8.10

**Comment by tikiMC** [comment]
Awesome! Thanks :D
